USE akoho;
DELETE FROM parametre;
INSERT INTO parametre (cle, valeur, label, type_input) VALUES ('limite_vente_active', '0', 'Activer limitation de vente', 'toggle');
INSERT INTO parametre (cle, valeur, label, type_input) VALUES ('limite_vente_semaine', '6', 'Semaine minimale pour vendre des poulets', 'number');
INSERT INTO parametre (cle, valeur, label, type_input) VALUES ('limite_vente_poids_kg', '0.5', 'Poids minimum pour vendre (kg)', 'number');
INSERT INTO parametre (cle, valeur, label, type_input) VALUES ('arret_poids_active', '0', 'Activer arret progression du poids', 'toggle');
INSERT INTO parametre (cle, valeur, label, type_input) VALUES ('arret_poids_semaine', '25', 'Semaine arret de progression du poids', 'number');
INSERT INTO parametre (cle, valeur, label, type_input) VALUES ('fiche_defaut_active', '1', 'Utiliser fiche par defaut si semaines manquantes', 'toggle');
DELETE FROM fiche_defaut_row;
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (1, 45, 30);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (2, 50, 45);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (3, 48, 55);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (4, 45, 65);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (5, 40, 80);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (6, 35, 95);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (7, 30, 110);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (8, 28, 125);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (9, 25, 135);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (10, 22, 145);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (11, 20, 155);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (12, 18, 165);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (13, 16, 175);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (14, 14, 182);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (15, 12, 190);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (16, 10, 196);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (17, 9, 202);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (18, 8, 208);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (19, 7, 212);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (20, 6, 216);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (21, 5, 220);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (22, 5, 224);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (23, 4, 227);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (24, 4, 230);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (25, 3, 232);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (26, 3, 234);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (27, 2, 235);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (28, 2, 236);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (29, 1, 237);
INSERT INTO fiche_defaut_row (semaine, variation, poids) VALUES (30, 1, 238);
SELECT COUNT(*) AS nb_params FROM parametre;
SELECT COUNT(*) AS nb_fiche_rows FROM fiche_defaut_row;
PRINT 'Data inserted OK';
